/**
 * The append-only, per-attempt evidence ledger (tasks 7.1-7.4 of
 * `add-agentic-review-harness`, design.md D8, spec `review-evidence-ledger`).
 *
 * One ledger exists per harness attempt. It records every exact payload a
 * host tool returned to the model as a frozen `LedgerEvidenceSource`: the
 * D8 `EvidenceSource` fields (task 2.5) plus the binding task 7.2 requires —
 * run/lineage/attempt, changeset member, origin, trust, citable status, the
 * exact citable locations, byte length, and truncation metadata. Records are
 * never mutated, replaced, or removed: the only write operations append,
 * every returned record is deep-frozen, and `sources()` hands out a copy.
 *
 * Resolved design questions, so later sections do not re-litigate them:
 *
 * - **Exact bytes live in memory** (D8: "in-memory ledger ... `exactContent:
 *   string`"). Persisting only digests plus the excerpts retained citations
 *   need is section 11's `HarnessRunStore`, which reads from this ledger; the
 *   ledger itself never writes anywhere. `maxEvidenceBytesPerAttempt` from
 *   `HarnessPolicy` bounds the in-memory total, and a payload that does not
 *   fit is *refused* (nothing is returned to the model), never silently cut.
 * - **`sourceId` is opaque and unguessable**: `ev_` plus 128 random bits from
 *   `node:crypto`, generated by the ledger, never derived from path/range/
 *   content — so untrusted content cannot pre-compute a valid identifier and
 *   a citation cannot name a payload the model was never shown. Identifiers
 *   are attempt-bound by construction: they resolve only in the ledger that
 *   minted (or explicitly imported) them. D8's "stable inside the lineage"
 *   is `importRetainedSource`: a resumed attempt reuses the prior identifier
 *   only when the exact content is present and its digest and member
 *   snapshot still match; otherwise the new attempt must refetch.
 * - **Digest** is `sha256Hex` over the canonical bytes of what the model saw
 *   (`./contentDigest`): raw text for diff/file/attachment/policy/intent and
 *   sorted-key canonical JSON for structured search/detail payloads.
 * - **Citation authority is a source-category allowlist** (`CITABLE_ORIGINS`),
 *   not a per-record flag a caller can set: `citable` is derived from `origin`
 *   inside `append`, so intent, detail pages, and every `AGENTS.md` level are
 *   non-citable by construction (task 7.4, section-6 note in
 *   `harnessBootstrap.ts`), diff evidence and explicit attachments citable.
 * - **Only model-visible results register** (task 7.3): every provider-backed
 *   `register*` takes the neutral `InvestigationResult` and refuses any state
 *   without a `value` (`unavailable`, `binary`, `tooLarge`, `notFound`,
 *   `unknown`) — a partial or failed provider state can never become a
 *   citable record. The dispatcher (section 9) is expected to return
 *   `source.exactContent` to the model, so the bytes recorded and the bytes
 *   shown are the same string.
 * - **Cross-head / cross-member aliasing is rejected** at registration: a
 *   result whose `snapshot` differs from the declared member's repository,
 *   base, or head is refused, so evidence from another head can never sit
 *   under this attempt's identifiers (spec: "evidence from the two heads is
 *   never combined into one finding").
 *
 * - **Every record names the source that produced it** (`producedBy`,
 *   `add-local-git-investigation` task 10.1). Derived inside `append` from the
 *   origin and the member's recorded investigation source, never accepted from
 *   a caller, and carried through persistence so a resumed attempt and a
 *   diagnostics report read what the fetching attempt recorded rather than
 *   re-deriving it from whatever source is selected now.
 *
 * Trust: every author-controlled payload (diff, file, search, detail,
 * attachment, intent) is `untrusted`; `AGENTS.md` policy is `authoritative`
 * but non-citable — the same split `harnessBootstrap.ts` documents.
 */
import { randomBytes } from 'node:crypto';
import { canonicalStringify, sha256Hex } from './contentDigest';
import type { AgentsPolicyLevel } from './harnessAgentsPolicy';
import { normalizeModelVisiblePath } from './modelVisiblePath';
import { attachmentEvidenceManifest, type Attachment } from './reviewContext';
import { parseHunks } from '../domain/diffHunks';
import type { EvidenceCompleteness, EvidenceKind, EvidenceRange, EvidenceSource } from '../domain/harnessEvidence';
import type { AttemptNumber, LineageId, RunId } from '../domain/harnessLifecycle';
import { DEFAULT_HARNESS_POLICY, type HarnessPolicy } from '../domain/harnessPolicy';
import { investigationSourceKindOf, type InvestigationSourceKind, type ReviewRunSnapshot } from '../domain/reviewRunSnapshot';
import type {
  ChangeRequestDetailResult,
  DiffPageResult,
  DiffSearchRequest,
  DiffSearchResult,
  FileRangeResult,
  InvestigationResult,
  InvestigationSnapshotRef,
  IssueDetailResult,
  PinnedRevision,
  RepositorySearchRequest,
  RepositorySearchResult,
} from '../platform/types';

export const EVIDENCE_ORIGINS = [
  'diffPage',
  'fileRange',
  'repositorySearch',
  'diffSearch',
  'changeRequestDetail',
  'issueDetail',
  'agentsPolicy',
  'attachment',
  'intent',
] as const;

/** Which host tool (or bootstrap channel) produced a payload — the category the citation allowlist keys on. */
export type EvidenceOrigin = (typeof EVIDENCE_ORIGINS)[number];

/** Task 7.4's allowlist: the only origins a finding may cite. Everything else is intent or policy. */
export const CITABLE_ORIGINS: ReadonlySet<EvidenceOrigin> = new Set<EvidenceOrigin>([
  'diffPage',
  'fileRange',
  'repositorySearch',
  'diffSearch',
  'attachment',
]);

export type EvidenceTrust = 'untrusted' | 'authoritative';

export const EVIDENCE_PRODUCERS = ['localGit', 'sample', 'provider', 'host'] as const;

/**
 * Which source actually produced a payload — task 10.1 of
 * `add-local-git-investigation`.
 *
 * Three of the four values are `InvestigationSourceKind`'s own
 * (`../domain/reviewRunSnapshot.ts`), deliberately the same words the member
 * snapshot records, so a coverage report, a limitation and a diagnostic all
 * name a source the same way rather than each inventing a label. `provider` is
 * among them for the records already on disk: nothing produces one now, because
 * no investigation reaches a forge. The fourth, `host`, is for the payloads no
 * investigation source ever sees: a reviewer's attachment and the host's own
 * derived intent.
 *
 * Why per record rather than per run: a changeset's members each have their own
 * object store, and a stored ledger can hold records written under an older
 * build, so a run still reports truthfully where each fact came from.
 */
export type EvidenceProducer = (typeof EVIDENCE_PRODUCERS)[number];

/**
 * Which source answers this origin, given the source the member's snapshot
 * recorded for investigation.
 *
 * Exhaustive on purpose, with no default arm: a new `EvidenceOrigin` must
 * state where its content comes from, and the alternative — falling through to
 * `provider` — is how a locally computed fact would quietly be attributed to a
 * forge that never served it.
 *
 * The split follows design D2 as the rule sharpened it: everything answerable
 * from two commits comes from the selected source — the four investigation
 * payloads *and* the `AGENTS.md` walk `resolvePolicy` runs, which reads a file
 * in the repository at the base revision. Only change-request and issue detail
 * stay with the connection, because neither is in the repository at all
 * (`harnessToolDispatcher.ts`'s `dispatchTargetFor`).
 */
export function evidenceProducerFor(origin: EvidenceOrigin, investigationSource: InvestigationSourceKind): EvidenceProducer {
  switch (origin) {
    case 'diffPage':
    case 'fileRange':
    case 'repositorySearch':
    case 'diffSearch':
      return investigationSource;
    case 'agentsPolicy':
      return investigationSource;
    case 'changeRequestDetail':
    case 'issueDetail':
      return 'provider';
    case 'attachment':
    case 'intent':
      return 'host';
    default: {
      const exhaustive: never = origin;
      return exhaustive;
    }
  }
}

/** One exact span the model saw — what a citation's path/range must fall inside. `side` exists only for diff positions. */
export interface EvidenceLocation {
  readonly path: string;
  readonly range: EvidenceRange;
  readonly side?: 'old' | 'new';
}

export interface EvidenceTruncation {
  /** A provider continuation exists (state `paginated`); the ledger never stores the cursor itself. */
  readonly hasContinuation: boolean;
  readonly knownRemainingUnits?: number;
}

export interface LedgerEvidenceSource extends EvidenceSource {
  readonly runId: RunId;
  readonly lineageId: LineageId;
  /** The attempt whose ledger holds this record — not necessarily the attempt that first fetched it (see `importedFromAttempt`). */
  readonly attempt: AttemptNumber;
  readonly memberId: string;
  readonly origin: EvidenceOrigin;
  readonly trust: EvidenceTrust;
  /**
   * The source that produced these exact bytes (task 10.1), derived inside
   * `append` from the origin and the member's recorded investigation source —
   * never supplied by a caller, so nothing can label a payload with a source
   * that did not serve it.
   */
  readonly producedBy: EvidenceProducer;
  /** Position in this ledger's append order, starting at 1. */
  readonly sequence: number;
  readonly locations: readonly EvidenceLocation[];
  readonly byteLength: number;
  readonly truncation?: EvidenceTruncation;
  /** Attachments only: the snapshot's digest of the full attachment content (D8 "bound to their snapshot digest"). */
  readonly snapshotContentDigest?: string;
  /** Present only on a record reused from a prior attempt through `importRetainedSource`. */
  readonly importedFromAttempt?: AttemptNumber;
  /**
   * These bytes were fetched but never shown to the model — see `EvidenceLedger.revoke`. The
   * record stays in append order with its digest and byte count intact, because it really was
   * fetched and really was charged to this attempt's evidence budget; what it loses is
   * `citable`, and with it any path from a citation to a finding.
   */
  readonly revoked?: boolean;
}

export interface EvidenceLedgerMember {
  readonly memberId: string;
  readonly repositoryId: string;
  readonly baseSha: string;
  readonly headSha: string;
  readonly changeRequestNumber?: string;
  /**
   * Which kind of source answers this member's investigation (task 10.1).
   * Absent reads as `provider`, through `investigationSourceKindOf`'s own rule:
   * every record that predates source selection was served by a provider, and
   * treating absence as the fact it is beats treating it as unknown
   * (`../domain/reviewRunSnapshot.ts`).
   *
   * The kind, not the source: `harnessToolDispatcher.ts`'s `DispatcherMember`
   * extends this interface and carries the live source object itself under
   * `investigationSource`, and one name for two different things in one
   * structurally-typed member is how the wrong one gets read.
   */
  readonly investigationSourceKind?: InvestigationSourceKind;
}

export interface EvidenceLedgerIdentity {
  readonly runId: RunId;
  readonly lineageId: LineageId;
  readonly attempt: AttemptNumber;
}

export type RegistrationRefusal =
  | 'unknownMember'
  | 'snapshotMismatch'
  | 'notModelVisible'
  | 'exceedsResultBound'
  | 'evidenceBudgetExhausted'
  | 'invalidRange'
  | 'invalidPath'
  | 'digestMismatch'
  | 'duplicateSourceId'
  | 'exactContentUnavailable'
  | 'malformed';

export type RegistrationOutcome =
  | { readonly ok: true; readonly source: LedgerEvidenceSource }
  | { readonly ok: false; readonly code: RegistrationRefusal; readonly message: string };

type Refusal = Extract<RegistrationOutcome, { ok: false }>;

/** The shape section 11 persists and a resumed attempt offers back; exact content must be present to import. */
export interface RetainedEvidenceRecord {
  readonly sourceId: string;
  readonly digest: string;
  readonly kind: EvidenceKind;
  readonly origin: EvidenceOrigin;
  readonly memberId: string;
  readonly repositoryId: string;
  readonly baseSha: string;
  readonly headSha: string;
  readonly revision?: PinnedRevision;
  readonly path?: string;
  readonly range?: EvidenceRange;
  readonly completeness: EvidenceCompleteness;
  readonly locations: readonly EvidenceLocation[];
  readonly truncation?: EvidenceTruncation;
  readonly snapshotContentDigest?: string;
  readonly fetchedInAttempt: AttemptNumber;
  readonly exactContent?: string;
  /**
   * The source that produced these bytes, carried across persistence so a
   * resumed attempt and a diagnostics report read the same answer the fetching
   * attempt recorded (task 10.1). Optional because a record stored before this
   * field existed carries nothing; read it through `evidenceProducerOf`, never
   * with an inline `?? …`.
   */
  readonly producedBy?: EvidenceProducer;
}

/**
 * The producer a stored record was fetched under. Absence is a known fact, not
 * an unknown: every record written before task 10.1 came from a provider,
 * because no other source existed. Same shape and same reason as
 * `investigationSourceKindOf` and `baseRevisionKindOf`.
 */
export function evidenceProducerOf(record: Pick<RetainedEvidenceRecord, 'producedBy'>): EvidenceProducer {
  return record.producedBy ?? 'provider';
}

export interface EvidenceLedger {
  readonly identity: EvidenceLedgerIdentity;
  readonly members: readonly EvidenceLedgerMember[];
  member(memberId: string): EvidenceLedgerMember | undefined;
  get(sourceId: string): LedgerEvidenceSource | undefined;
  /** A fresh copy in append order; mutating it cannot reach the ledger. */
  sources(): readonly LedgerEvidenceSource[];
  readonly size: number;
  readonly bytesUsed: number;
  readonly maxEvidenceBytes: number;
  registerDiffPage(memberId: string, result: DiffPageResult): RegistrationOutcome;
  registerFileRange(memberId: string, result: FileRangeResult): RegistrationOutcome;
  registerRepositorySearch(memberId: string, request: RepositorySearchRequest, result: RepositorySearchResult): RegistrationOutcome;
  registerDiffSearch(memberId: string, request: DiffSearchRequest, result: DiffSearchResult): RegistrationOutcome;
  registerChangeRequestDetail(memberId: string, result: ChangeRequestDetailResult): RegistrationOutcome;
  registerIssueDetail(memberId: string, result: IssueDetailResult): RegistrationOutcome;
  /** An `AGENTS.md` level actually returned by `resolvePolicy`; always `authoritative` and non-citable. */
  registerAgentsPolicy(memberId: string, level: AgentsPolicyLevel): RegistrationOutcome;
  /** A reviewer-selected attachment as returned to the model: post-budget visible content, bound to the snapshot's content digest. */
  registerAttachment(memberId: string, attachment: Attachment, snapshotContentDigest: string): RegistrationOutcome;
  /** Auto-derived context (title, body, linked items, discussion) shown as intent; never citable. */
  registerIntent(memberId: string, label: string, text: string): RegistrationOutcome;
  /**
   * Withdraws one source's citability because the model was never shown it.
   *
   * **Why the ledger has to know.** This ledger's whole job is stated in `harnessToolDispatcher.ts`
   * — "every evidence-bearing handler registers into the ledger first" so that only content the
   * model actually received can support a finding. Registration happens at *dispatch*; the prompt
   * carrying the result is assembled afterwards, and `harnessModelSeam.ts` drops whole results
   * from an over-cap prompt. A source registered for a dropped result is a citable digest for
   * bytes that never reached a model — the one thing this ledger exists to refuse, arriving
   * through the host's own renderer.
   *
   * Marked, never deleted. The bytes were fetched and charged, so `bytesUsed` is unchanged and
   * `sequence` is unchanged: renumbering append order would silently rewrite the recency the
   * investigation map derives from it, and dropping the record would lose the audit trail of a
   * provider call this attempt really made. Returns `false` for an unknown source id, and is
   * idempotent for one already revoked.
   */
  revoke(sourceId: string): boolean;
  /** Resume path (D8): reuse a prior attempt's identifier only when exact content, digest, and member snapshot all still match. */
  importRetainedSource(record: RetainedEvidenceRecord): RegistrationOutcome;
}

export interface EvidenceLedgerOptions {
  /** Defaults to `DEFAULT_HARNESS_POLICY`'s result and per-attempt evidence bounds. */
  policy?: Pick<HarnessPolicy, 'maxToolResultBytes' | 'maxEvidenceBytesPerAttempt'>;
}

/** Members straight from the immutable snapshot, so ledger identity can never drift from what the run pinned. */
export function ledgerMembersFromSnapshot(snapshot: ReviewRunSnapshot): EvidenceLedgerMember[] {
  return snapshot.members.map((member) => ({
    memberId: member.memberId,
    repositoryId: member.ref.repoId,
    baseSha: member.baseSha,
    headSha: member.headSha,
    changeRequestNumber: member.ref.number,
    // Read off the snapshot the run pinned, so the producer stamped on a
    // record and the source kind a resume compares can never disagree.
    investigationSourceKind: investigationSourceKindOf(member),
  }));
}

export function isCitableOrigin(origin: EvidenceOrigin): boolean {
  return CITABLE_ORIGINS.has(origin);
}

const SOURCE_ID_PATTERN = /^ev_[0-9a-f]{32}$/;

export function isWellFormedSourceId(value: unknown): value is string {
  return typeof value === 'string' && SOURCE_ID_PATTERN.test(value);
}

function mintSourceId(): string {
  return `ev_${randomBytes(16).toString('hex')}`;
}

function isPositiveInteger(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && value >= 1;
}

/** Bounded and normalized: positive integers, `endLine` defaults to `startLine`, and never inverted. */
export function normalizeEvidenceRange(startLine: unknown, endLine?: unknown): EvidenceRange | undefined {
  if (!isPositiveInteger(startLine)) return undefined;
  if (endLine === undefined) return { startLine, endLine: startLine };
  if (!isPositiveInteger(endLine) || endLine < startLine) return undefined;
  return { startLine, endLine };
}

/**
 * A literal `%2e`/`%2f`/`%5c` (case-insensitive) anywhere refuses the path
 * outright rather than decoding and re-checking it (task 9.8 "encoded" path
 * traversal): this module never resolves a path against a real filesystem
 * or URL, so a legitimate repository path has no reason to carry a
 * percent-encoded dot or separator, and fail-closed here costs nothing a
 * real path would ever need. A leading `/` is deliberately *not* refused --
 * it is stripped and the remainder treated as repository-relative, the same
 * normalization `modelVisiblePath.ts` uses for multi-root workspace labels
 * (`harnessEvidenceLedger.test.ts` pins `'/src/a.ts' -> 'src/a.ts'`).
 */
const ENCODED_TRAVERSAL_OR_SEPARATOR = /%(?:2e|2f|5c)/i;

/** Representation-only normalization plus a refusal of anything that could escape a repository root. */
export function normalizeEvidencePath(path: unknown): string | undefined {
  if (typeof path !== 'string') return undefined;
  const normalized = normalizeModelVisiblePath(path).replace(/^\//, '');
  if (normalized === '' || normalized.includes('\u0000')) return undefined;
  if (ENCODED_TRAVERSAL_OR_SEPARATOR.test(normalized)) return undefined;
  if (normalized.split('/').some((segment) => segment === '..')) return undefined;
  return normalized;
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
  }
  return value;
}

function utf8ByteLength(text: string): number {
  return Buffer.byteLength(text, 'utf8');
}

interface PendingRecord {
  kind: EvidenceKind;
  origin: EvidenceOrigin;
  trust: EvidenceTrust;
  revision?: PinnedRevision;
  path?: string;
  range?: EvidenceRange;
  completeness: EvidenceCompleteness;
  locations: readonly EvidenceLocation[];
  truncation?: EvidenceTruncation;
  exactContent: string;
  snapshotContentDigest?: string;
  /** Only `importRetainedSource` supplies these. */
  sourceId?: string;
  importedFromAttempt?: AttemptNumber;
  /**
   * Only `importRetainedSource` supplies this, and it supplies the value the
   * fetching attempt stored: a record is attributed to the source that really
   * produced it, never re-derived from the attempt importing it.
   */
  producedBy?: EvidenceProducer;
}

function refuse(code: RegistrationRefusal, message: string): Refusal {
  return { ok: false, code, message };
}

function completenessOf<T>(result: InvestigationResult<T>): { completeness: EvidenceCompleteness; truncation?: EvidenceTruncation } | undefined {
  switch (result.state) {
    case 'complete':
      return { completeness: 'complete' };
    case 'paginated':
      return { completeness: 'paginated', truncation: { hasContinuation: true } };
    case 'truncated':
      return { completeness: 'truncated', truncation: { hasContinuation: false, knownRemainingUnits: result.knownRemainingUnits } };
    default:
      return undefined;
  }
}

/**
 * The citable spans a diff page carries in its own bytes, read from the patch
 * itself when the source named none.
 *
 * **The live failure this exists for.** A `DiffPage` declares `positions` as
 * "positions inside `patch` a citation can anchor to", and `registerDiffPage`
 * took a page's citable locations from that field alone. The only production
 * investigation source — `../localgit/localGitSource.ts` — returns
 * `positions: []` on every page, deliberately: a position per line would
 * multiply a 20,000-line page by a factor its declared byte bound does not
 * count. So every diff page in every real run held **zero** citable locations,
 * `../app/harnessCitations.ts`'s `resolveCitation` failed each primary citation
 * at `pathMismatch` ("Evidence ev_… did not return any content for <the very
 * path the page is of>"), and that failure is not repairable — so
 * `validateCandidate` rejected the candidate outright and never reached its own
 * location or verbatim-code checks. A live review of 245 changed files
 * submitted nine candidates and the host destroyed all nine. Every test that
 * exercised a diff page fabricated `positions` no source produces, which is why
 * this shipped green.
 *
 * The fix belongs here rather than in the source: the ledger already holds the
 * exact bytes, and one derivation here answers for every source instead of each
 * one re-walking its own patch.
 *
 * Spans come from the lines the parse actually produced, never from the `@@`
 * header's counts. That is the difference between a span the model was shown
 * and a span it was not: a page cut mid-hunk by pagination still carries the
 * header's full counts, and trusting them would make unshown lines citable —
 * exactly the guarantee this ledger exists to provide. One span per hunk per
 * side, new side first, because `locationContaining` returns the first
 * containing span and a citation that fits both sides is a citation about the
 * head state (`harnessSynthesisVerification.ts` reads `side` off the location
 * to cut its excerpt window).
 *
 * A continuation page (page 2+ of a diff over this source's 20,000-line /
 * 256KB bound) begins mid-hunk with no `@@` header, so `parseHunks` yields
 * nothing and the page stays uncitable, as it was before this existed. Known
 * and left: it needs the source to state the page's own span, and no diff of a
 * single file in this project's reviews has reached that bound.
 */
function diffPatchLocations(patch: string, newPath: string, oldPath: string): EvidenceLocation[] {
  const locations: EvidenceLocation[] = [];
  for (const hunk of parseHunks(patch)) {
    let newFirst: number | undefined;
    let newLast: number | undefined;
    let oldFirst: number | undefined;
    let oldLast: number | undefined;
    for (const line of hunk.lines) {
      if (line.newLine !== undefined) {
        newFirst ??= line.newLine;
        newLast = line.newLine;
      }
      if (line.oldLine !== undefined) {
        oldFirst ??= line.oldLine;
        oldLast = line.oldLine;
      }
    }
    if (newFirst !== undefined && newLast !== undefined) locations.push({ path: newPath, range: { startLine: newFirst, endLine: newLast }, side: 'new' });
    if (oldFirst !== undefined && oldLast !== undefined) locations.push({ path: oldPath, range: { startLine: oldFirst, endLine: oldLast }, side: 'old' });
  }
  return locations;
}

export function createEvidenceLedger(
  identity: EvidenceLedgerIdentity,
  members: readonly EvidenceLedgerMember[],
  options: EvidenceLedgerOptions = {},
): EvidenceLedger {
  if (members.length === 0) throw new Error('An evidence ledger needs at least one member.');
  const memberIds = new Set<string>();
  for (const member of members) {
    if (memberIds.has(member.memberId)) throw new Error(`Duplicate ledger member id: ${member.memberId}`);
    memberIds.add(member.memberId);
  }
  const policy = options.policy ?? DEFAULT_HARNESS_POLICY;
  const maxResultBytes = policy.maxToolResultBytes;
  const maxEvidenceBytes = policy.maxEvidenceBytesPerAttempt;
  const frozenIdentity = deepFreeze({ ...identity });
  const frozenMembers = deepFreeze(members.map((member) => ({ ...member })));
  const byMemberId = new Map(frozenMembers.map((member) => [member.memberId, member] as const));

  const records: LedgerEvidenceSource[] = [];
  const bySourceId = new Map<string, LedgerEvidenceSource>();
  let bytesUsed = 0;

  function memberFor(memberId: string): EvidenceLedgerMember | undefined {
    return byMemberId.get(memberId);
  }

  function snapshotMatches(member: EvidenceLedgerMember, snapshot: InvestigationSnapshotRef): boolean {
    return snapshot.repoId === member.repositoryId && snapshot.baseSha === member.baseSha && snapshot.headSha === member.headSha;
  }

  /** The single append path: every invariant is checked here, whatever the origin. */
  function append(member: EvidenceLedgerMember, pending: PendingRecord): RegistrationOutcome {
    const byteLength = utf8ByteLength(pending.exactContent);
    if (byteLength > maxResultBytes) {
      return refuse('exceedsResultBound', `Payload is ${byteLength} bytes; one tool result may return at most ${maxResultBytes}.`);
    }
    if (bytesUsed + byteLength > maxEvidenceBytes) {
      return refuse('evidenceBudgetExhausted', `Registering ${byteLength} bytes would exceed the ${maxEvidenceBytes}-byte evidence budget for this attempt.`);
    }
    for (const location of pending.locations) {
      if (normalizeEvidencePath(location.path) !== location.path) return refuse('invalidPath', `Location path is not normalized: ${location.path}`);
      if (!normalizeEvidenceRange(location.range.startLine, location.range.endLine)) {
        return refuse('invalidRange', `Location range is not a bounded positive line range: ${location.path}`);
      }
    }
    if (pending.path !== undefined && normalizeEvidencePath(pending.path) !== pending.path) {
      return refuse('invalidPath', `Source path is not normalized: ${pending.path}`);
    }
    if (pending.range && !normalizeEvidenceRange(pending.range.startLine, pending.range.endLine)) {
      return refuse('invalidRange', 'Source range is not a bounded positive line range.');
    }
    const sourceId = pending.sourceId ?? mintSourceId();
    if (bySourceId.has(sourceId)) return refuse('duplicateSourceId', `Source ${sourceId} is already in this ledger.`);

    const source: LedgerEvidenceSource = deepFreeze({
      sourceId,
      digest: sha256Hex(pending.exactContent),
      kind: pending.kind,
      repositoryId: member.repositoryId,
      baseSha: member.baseSha,
      headSha: member.headSha,
      revision: pending.revision,
      path: pending.path,
      range: pending.range,
      completeness: pending.completeness,
      citable: isCitableOrigin(pending.origin),
      exactContent: pending.exactContent,
      runId: frozenIdentity.runId,
      lineageId: frozenIdentity.lineageId,
      attempt: frozenIdentity.attempt,
      memberId: member.memberId,
      origin: pending.origin,
      trust: pending.trust,
      producedBy: pending.producedBy ?? evidenceProducerFor(pending.origin, member.investigationSourceKind ?? 'provider'),
      sequence: records.length + 1,
      locations: pending.locations.map((location) => ({ ...location, range: { ...location.range } })),
      byteLength,
      truncation: pending.truncation,
      snapshotContentDigest: pending.snapshotContentDigest,
      importedFromAttempt: pending.importedFromAttempt,
    });
    records.push(source);
    bySourceId.set(sourceId, source);
    bytesUsed += byteLength;
    return { ok: true, source };
  }

  /** Common gate for every provider-backed result: member known, snapshot pinned to it, and a model-visible state. */
  function admitResult<T>(
    memberId: string,
    result: InvestigationResult<T>,
  ): { ok: true; member: EvidenceLedgerMember; value: T; completeness: EvidenceCompleteness; truncation?: EvidenceTruncation } | Refusal {
    const member = memberFor(memberId);
    if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
    if (!snapshotMatches(member, result.snapshot)) {
      return refuse('snapshotMismatch', `Result is pinned to ${result.snapshot.repoId}@${result.snapshot.baseSha}..${result.snapshot.headSha}, not member ${memberId}'s snapshot.`);
    }
    const shape = completenessOf(result);
    if (!shape) return refuse('notModelVisible', `A "${result.state}" result carries no content the model can see.`);
    return { ok: true, member, value: (result as { value: T }).value, ...shape };
  }

  function isRefusal(value: { ok: boolean }): value is Refusal {
    return value.ok === false;
  }

  const ledger: EvidenceLedger = {
    identity: frozenIdentity,
    members: frozenMembers,
    member: memberFor,
    get: (sourceId) => bySourceId.get(sourceId),
    sources: () => [...records],
    revoke: (sourceId) => {
      const existing = bySourceId.get(sourceId);
      if (existing === undefined) return false;
      if (existing.revoked === true) return true;
      const revoked = deepFreeze({ ...existing, citable: false, revoked: true });
      const index = records.indexOf(existing);
      if (index >= 0) records[index] = revoked;
      bySourceId.set(sourceId, revoked);
      return true;
    },
    get size() {
      return records.length;
    },
    get bytesUsed() {
      return bytesUsed;
    },
    maxEvidenceBytes,

    registerDiffPage(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      const page = admitted.value;
      const path = normalizeEvidencePath(page.path);
      if (!path) return refuse('invalidPath', `Diff page path is not usable: ${String(page.path)}`);
      const locations: EvidenceLocation[] = [];
      for (const position of page.positions) {
        const positionPath = normalizeEvidencePath(position.path);
        const range = normalizeEvidenceRange(position.line, position.endLine);
        if (!positionPath) return refuse('invalidPath', `Diff position path is not usable: ${String(position.path)}`);
        if (!range) return refuse('invalidRange', `Diff position has an invalid line range at ${positionPath}.`);
        locations.push({ path: positionPath, range, side: position.side });
      }
      // A source that named its own positions has spoken; only silence is
      // answered from the patch (see `diffPatchLocations` for the live failure
      // that made a silent source mean "nothing here is citable").
      if (locations.length === 0) {
        const oldPath = page.oldPath === undefined ? path : normalizeEvidencePath(page.oldPath);
        if (!oldPath) return refuse('invalidPath', `Diff page old path is not usable: ${String(page.oldPath)}`);
        locations.push(...diffPatchLocations(page.patch, path, oldPath));
      }
      return append(admitted.member, {
        kind: 'diff',
        origin: 'diffPage',
        trust: 'untrusted',
        path,
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations,
        exactContent: page.patch,
      });
    },

    registerFileRange(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      const file = admitted.value;
      const path = normalizeEvidencePath(file.path);
      const range = normalizeEvidenceRange(file.startLine, file.endLine);
      if (!path) return refuse('invalidPath', `File range path is not usable: ${String(file.path)}`);
      if (!range) return refuse('invalidRange', `File range ${String(file.startLine)}-${String(file.endLine)} is not a bounded positive line range.`);
      return append(admitted.member, {
        kind: 'file',
        origin: 'fileRange',
        trust: 'untrusted',
        revision: file.revision,
        path,
        range,
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations: [{ path, range }],
        exactContent: file.text,
      });
    },

    registerRepositorySearch(memberId, request, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      if (!snapshotMatches(admitted.member, request.snapshot)) {
        return refuse('snapshotMismatch', 'Search request and result are pinned to different snapshots.');
      }
      const locations: EvidenceLocation[] = [];
      const canonicalMatches: Array<{ path: string; line: number; excerpt: string }> = [];
      for (const match of admitted.value) {
        const path = normalizeEvidencePath(match.path);
        const range = normalizeEvidenceRange(match.line);
        if (!path) return refuse('invalidPath', `Search match path is not usable: ${String(match.path)}`);
        if (!range) return refuse('invalidRange', `Search match line is invalid at ${path}.`);
        locations.push({ path, range });
        canonicalMatches.push({ path, line: match.line, excerpt: match.excerpt });
      }
      return append(admitted.member, {
        kind: 'searchExcerpt',
        origin: 'repositorySearch',
        trust: 'untrusted',
        revision: request.revision,
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations,
        exactContent: canonicalStringify(canonicalMatches),
      });
    },

    registerDiffSearch(memberId, request, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      if (!snapshotMatches(admitted.member, request.snapshot)) {
        return refuse('snapshotMismatch', 'Search request and result are pinned to different snapshots.');
      }
      const locations: EvidenceLocation[] = [];
      const canonicalMatches: Array<{ path: string; side: 'old' | 'new'; line: number; endLine?: number; excerpt: string }> = [];
      for (const match of admitted.value) {
        const path = normalizeEvidencePath(match.position.path);
        const range = normalizeEvidenceRange(match.position.line, match.position.endLine);
        if (!path) return refuse('invalidPath', `Diff search match path is not usable: ${String(match.position.path)}`);
        if (!range) return refuse('invalidRange', `Diff search match has an invalid line range at ${path}.`);
        locations.push({ path, range, side: match.position.side });
        canonicalMatches.push({ path, side: match.position.side, line: match.position.line, endLine: match.position.endLine, excerpt: match.excerpt });
      }
      return append(admitted.member, {
        kind: 'searchExcerpt',
        origin: 'diffSearch',
        trust: 'untrusted',
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations,
        exactContent: canonicalStringify(canonicalMatches),
      });
    },

    registerChangeRequestDetail(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      return append(admitted.member, {
        kind: 'detail',
        origin: 'changeRequestDetail',
        trust: 'untrusted',
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations: [],
        exactContent: canonicalStringify(admitted.value),
      });
    },

    registerIssueDetail(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      return append(admitted.member, {
        kind: 'detail',
        origin: 'issueDetail',
        trust: 'untrusted',
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations: [],
        exactContent: canonicalStringify(admitted.value),
      });
    },

    registerAgentsPolicy(memberId, level) {
      const member = memberFor(memberId);
      if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
      if (level.state !== 'present') return refuse('notModelVisible', `An "${level.state}" AGENTS.md level has no content.`);
      if (sha256Hex(level.content) !== level.digest) {
        return refuse('digestMismatch', 'AGENTS.md level digest does not match its content.');
      }
      const path = normalizeEvidencePath(level.directory === '' ? 'AGENTS.md' : `${level.directory}/AGENTS.md`);
      if (!path) return refuse('invalidPath', `AGENTS.md directory is not usable: ${level.directory}`);
      return append(member, {
        kind: 'file',
        origin: 'agentsPolicy',
        trust: 'authoritative',
        revision: 'base',
        path,
        completeness: 'complete',
        locations: [],
        exactContent: level.content,
      });
    },

    registerAttachment(memberId, attachment, snapshotContentDigest) {
      const member = memberFor(memberId);
      if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
      if (typeof attachment.content !== 'string') return refuse('malformed', 'Attachment has no content.');
      if (sha256Hex(attachment.content) !== snapshotContentDigest) {
        return refuse('digestMismatch', `Attachment ${attachment.id} does not match the content digest pinned in the run snapshot.`);
      }
      const visibleLength = Math.min(attachment.content.length, attachment.visibleContentLength ?? attachment.content.length);
      const exactContent = attachment.content.slice(0, visibleLength);
      const locations: EvidenceLocation[] = [];
      for (const entry of attachmentEvidenceManifest([attachment])) {
        const path = normalizeEvidencePath(entry.path);
        if (!path) return refuse('invalidPath', `Attachment evidence path is not usable: ${entry.path}`);
        for (const range of entry.ranges) {
          const normalized = normalizeEvidenceRange(range.startLine, range.endLine);
          if (!normalized) return refuse('invalidRange', `Attachment evidence range is invalid at ${path}.`);
          locations.push({ path, range: normalized });
        }
      }
      const path = normalizeEvidencePath(attachment.path);
      return append(member, {
        kind: 'attachment',
        origin: 'attachment',
        trust: 'untrusted',
        path,
        range: locations.length === 1 ? locations[0]?.range : undefined,
        completeness: visibleLength < attachment.content.length || attachment.truncated ? 'truncated' : 'complete',
        truncation: visibleLength < attachment.content.length || attachment.truncated ? { hasContinuation: false } : undefined,
        locations,
        exactContent,
        snapshotContentDigest,
      });
    },

    registerIntent(memberId, label, text) {
      const member = memberFor(memberId);
      if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
      if (typeof text !== 'string' || label.trim() === '') return refuse('malformed', 'Intent needs a label and text.');
      return append(member, {
        kind: 'detail',
        origin: 'intent',
        trust: 'untrusted',
        completeness: 'complete',
        locations: [],
        exactContent: canonicalStringify({ label, text }),
      });
    },

    importRetainedSource(record) {
      const member = memberFor(record.memberId);
      if (!member) return refuse('unknownMember', `Member ${record.memberId} is not part of this run.`);
      if (record.repositoryId !== member.repositoryId || record.baseSha !== member.baseSha || record.headSha !== member.headSha) {
        return refuse('snapshotMismatch', `Retained source ${record.sourceId} was fetched on a different repository or revision.`);
      }
      if (!isWellFormedSourceId(record.sourceId)) return refuse('malformed', 'Retained source identifier is not well-formed.');
      if (typeof record.exactContent !== 'string') {
        return refuse('exactContentUnavailable', `Retained source ${record.sourceId} has no exact content; it must be fetched again.`);
      }
      if (sha256Hex(record.exactContent) !== record.digest) {
        return refuse('digestMismatch', `Retained source ${record.sourceId} content no longer matches its digest.`);
      }
      if (!EVIDENCE_ORIGINS.includes(record.origin)) return refuse('malformed', `Unknown evidence origin: ${String(record.origin)}`);
      // Second line of defence for task 9.8, and one line of it: a resume
      // across a source-kind change is already refused whole by
      // `harnessResume.ts`, so this can only fire for a record assembled by
      // hand. It is worth the line anyway — importing keeps the prior
      // attempt's identifier, and an identifier that survives into a ledger
      // whose member is served by another source is evidence attributed to a
      // source that never produced it.
      const producedBy = evidenceProducerOf(record);
      if (producedBy !== evidenceProducerFor(record.origin, member.investigationSourceKind ?? 'provider')) {
        return refuse('snapshotMismatch', `Retained source ${record.sourceId} was produced by a different investigation source than this attempt's.`);
      }
      return append(member, {
        producedBy,
        sourceId: record.sourceId,
        kind: record.kind,
        origin: record.origin,
        trust: record.origin === 'agentsPolicy' ? 'authoritative' : 'untrusted',
        revision: record.revision,
        path: record.path,
        range: record.range,
        completeness: record.completeness,
        truncation: record.truncation,
        locations: record.locations,
        exactContent: record.exactContent,
        snapshotContentDigest: record.snapshotContentDigest,
        importedFromAttempt: record.fetchedInAttempt,
      });
    },
  };

  return ledger;
}

/** What section 11 may persist for one source: everything except (optionally) the exact bytes. */
export function toRetainedEvidenceRecord(source: LedgerEvidenceSource, options: { includeExactContent: boolean }): RetainedEvidenceRecord {
  return {
    sourceId: source.sourceId,
    digest: source.digest,
    kind: source.kind,
    origin: source.origin,
    memberId: source.memberId,
    repositoryId: source.repositoryId,
    baseSha: source.baseSha,
    headSha: source.headSha,
    revision: source.revision,
    path: source.path,
    range: source.range,
    completeness: source.completeness,
    locations: source.locations,
    truncation: source.truncation,
    snapshotContentDigest: source.snapshotContentDigest,
    fetchedInAttempt: source.importedFromAttempt ?? source.attempt,
    producedBy: source.producedBy,
    exactContent: options.includeExactContent ? source.exactContent : undefined,
  };
}
