/**
 * The append-only, per-attempt evidence ledger (tasks 7.1-7.4 of
 * `add-agentic-review-harness`, design.md D8, spec `review-evidence-ledger`).
 *
 * One ledger exists per harness attempt. It records every exact payload a
 * host tool returned to the model as a frozen `LedgerEvidenceSource`: the
 * D8 `EvidenceSource` fields (task 2.5) plus the binding task 7.2 requires —
 * run/lineage/attempt, changeset member, origin, trust, citable status, the
 * exact citable locations, byte length, and truncation metadata. Records are
 * never mutated, replaced, or removed: the only write operations append,
 * every returned record is deep-frozen, and `sources()` hands out a copy.
 *
 * Resolved design questions, so later sections do not re-litigate them:
 *
 * - **Exact bytes live in memory** (D8: "in-memory ledger ... `exactContent:
 *   string`"). Persisting only digests plus the excerpts retained citations
 *   need is section 11's `HarnessRunStore`, which reads from this ledger; the
 *   ledger itself never writes anywhere. `maxEvidenceBytesPerAttempt` from
 *   `HarnessPolicy` bounds the in-memory total, and a payload that does not
 *   fit is *refused* (nothing is returned to the model), never silently cut.
 * - **`sourceId` is opaque and unguessable**: `ev_` plus 128 random bits from
 *   `node:crypto`, generated by the ledger, never derived from path/range/
 *   content — so untrusted content cannot pre-compute a valid identifier and
 *   a citation cannot name a payload the model was never shown. Identifiers
 *   are attempt-bound by construction: they resolve only in the ledger that
 *   minted (or explicitly imported) them. D8's "stable inside the lineage"
 *   is `importRetainedSource`: a resumed attempt reuses the prior identifier
 *   only when the exact content is present and its digest and member
 *   snapshot still match; otherwise the new attempt must refetch.
 * - **Digest** is `sha256Hex` over the canonical bytes of what the model saw
 *   (`./contentDigest`): raw text for diff/file/attachment/policy/intent and
 *   sorted-key canonical JSON for structured search/detail payloads.
 * - **Citation authority is a source-category allowlist** (`CITABLE_ORIGINS`),
 *   not a per-record flag a caller can set: `citable` is derived from `origin`
 *   inside `append`, so intent, detail pages, and every `AGENTS.md` level are
 *   non-citable by construction (task 7.4, section-6 note in
 *   `harnessBootstrap.ts`), diff evidence and explicit attachments citable.
 * - **Only model-visible results register** (task 7.3): every provider-backed
 *   `register*` takes the neutral `InvestigationResult` and refuses any state
 *   without a `value` (`unavailable`, `binary`, `tooLarge`, `notFound`,
 *   `unknown`) — a partial or failed provider state can never become a
 *   citable record. The dispatcher (section 9) is expected to return
 *   `source.exactContent` to the model, so the bytes recorded and the bytes
 *   shown are the same string.
 * - **Cross-head / cross-member aliasing is rejected** at registration: a
 *   result whose `snapshot` differs from the declared member's repository,
 *   base, or head is refused, so evidence from another head can never sit
 *   under this attempt's identifiers (spec: "evidence from the two heads is
 *   never combined into one finding").
 *
 * Trust: every author-controlled payload (diff, file, search, detail,
 * attachment, intent) is `untrusted`; `AGENTS.md` policy is `authoritative`
 * but non-citable — the same split `harnessBootstrap.ts` documents.
 */
import { randomBytes } from 'node:crypto';
import { canonicalStringify, sha256Hex } from './contentDigest';
import type { AgentsPolicyLevel } from './harnessAgentsPolicy';
import { normalizeModelVisiblePath } from './modelVisiblePath';
import { attachmentEvidenceManifest, type Attachment } from './reviewContext';
import type { EvidenceCompleteness, EvidenceKind, EvidenceRange, EvidenceSource } from '../domain/harnessEvidence';
import type { AttemptNumber, LineageId, RunId } from '../domain/harnessLifecycle';
import { DEFAULT_HARNESS_POLICY, type HarnessPolicy } from '../domain/harnessPolicy';
import type { ReviewRunSnapshot } from '../domain/reviewRunSnapshot';
import type {
  ChangeRequestDetailResult,
  DiffPageResult,
  DiffSearchRequest,
  DiffSearchResult,
  FileRangeResult,
  InvestigationResult,
  InvestigationSnapshotRef,
  IssueDetailResult,
  PinnedRevision,
  RepositorySearchRequest,
  RepositorySearchResult,
} from '../platform/types';

export const EVIDENCE_ORIGINS = [
  'diffPage',
  'fileRange',
  'repositorySearch',
  'diffSearch',
  'changeRequestDetail',
  'issueDetail',
  'agentsPolicy',
  'attachment',
  'intent',
] as const;

/** Which host tool (or bootstrap channel) produced a payload — the category the citation allowlist keys on. */
export type EvidenceOrigin = (typeof EVIDENCE_ORIGINS)[number];

/** Task 7.4's allowlist: the only origins a finding may cite. Everything else is intent or policy. */
export const CITABLE_ORIGINS: ReadonlySet<EvidenceOrigin> = new Set<EvidenceOrigin>([
  'diffPage',
  'fileRange',
  'repositorySearch',
  'diffSearch',
  'attachment',
]);

export type EvidenceTrust = 'untrusted' | 'authoritative';

/** One exact span the model saw — what a citation's path/range must fall inside. `side` exists only for diff positions. */
export interface EvidenceLocation {
  readonly path: string;
  readonly range: EvidenceRange;
  readonly side?: 'old' | 'new';
}

export interface EvidenceTruncation {
  /** A provider continuation exists (state `paginated`); the ledger never stores the cursor itself. */
  readonly hasContinuation: boolean;
  readonly knownRemainingUnits?: number;
}

export interface LedgerEvidenceSource extends EvidenceSource {
  readonly runId: RunId;
  readonly lineageId: LineageId;
  /** The attempt whose ledger holds this record — not necessarily the attempt that first fetched it (see `importedFromAttempt`). */
  readonly attempt: AttemptNumber;
  readonly memberId: string;
  readonly origin: EvidenceOrigin;
  readonly trust: EvidenceTrust;
  /** Position in this ledger's append order, starting at 1. */
  readonly sequence: number;
  readonly locations: readonly EvidenceLocation[];
  readonly byteLength: number;
  readonly truncation?: EvidenceTruncation;
  /** Attachments only: the snapshot's digest of the full attachment content (D8 "bound to their snapshot digest"). */
  readonly snapshotContentDigest?: string;
  /** Present only on a record reused from a prior attempt through `importRetainedSource`. */
  readonly importedFromAttempt?: AttemptNumber;
}

export interface EvidenceLedgerMember {
  readonly memberId: string;
  readonly repositoryId: string;
  readonly baseSha: string;
  readonly headSha: string;
  readonly changeRequestNumber?: string;
}

export interface EvidenceLedgerIdentity {
  readonly runId: RunId;
  readonly lineageId: LineageId;
  readonly attempt: AttemptNumber;
}

export type RegistrationRefusal =
  | 'unknownMember'
  | 'snapshotMismatch'
  | 'notModelVisible'
  | 'exceedsResultBound'
  | 'evidenceBudgetExhausted'
  | 'invalidRange'
  | 'invalidPath'
  | 'digestMismatch'
  | 'duplicateSourceId'
  | 'exactContentUnavailable'
  | 'malformed';

export type RegistrationOutcome =
  | { readonly ok: true; readonly source: LedgerEvidenceSource }
  | { readonly ok: false; readonly code: RegistrationRefusal; readonly message: string };

type Refusal = Extract<RegistrationOutcome, { ok: false }>;

/** The shape section 11 persists and a resumed attempt offers back; exact content must be present to import. */
export interface RetainedEvidenceRecord {
  readonly sourceId: string;
  readonly digest: string;
  readonly kind: EvidenceKind;
  readonly origin: EvidenceOrigin;
  readonly memberId: string;
  readonly repositoryId: string;
  readonly baseSha: string;
  readonly headSha: string;
  readonly revision?: PinnedRevision;
  readonly path?: string;
  readonly range?: EvidenceRange;
  readonly completeness: EvidenceCompleteness;
  readonly locations: readonly EvidenceLocation[];
  readonly truncation?: EvidenceTruncation;
  readonly snapshotContentDigest?: string;
  readonly fetchedInAttempt: AttemptNumber;
  readonly exactContent?: string;
}

export interface EvidenceLedger {
  readonly identity: EvidenceLedgerIdentity;
  readonly members: readonly EvidenceLedgerMember[];
  member(memberId: string): EvidenceLedgerMember | undefined;
  get(sourceId: string): LedgerEvidenceSource | undefined;
  /** A fresh copy in append order; mutating it cannot reach the ledger. */
  sources(): readonly LedgerEvidenceSource[];
  readonly size: number;
  readonly bytesUsed: number;
  readonly maxEvidenceBytes: number;
  registerDiffPage(memberId: string, result: DiffPageResult): RegistrationOutcome;
  registerFileRange(memberId: string, result: FileRangeResult): RegistrationOutcome;
  registerRepositorySearch(memberId: string, request: RepositorySearchRequest, result: RepositorySearchResult): RegistrationOutcome;
  registerDiffSearch(memberId: string, request: DiffSearchRequest, result: DiffSearchResult): RegistrationOutcome;
  registerChangeRequestDetail(memberId: string, result: ChangeRequestDetailResult): RegistrationOutcome;
  registerIssueDetail(memberId: string, result: IssueDetailResult): RegistrationOutcome;
  /** An `AGENTS.md` level actually returned by `resolvePolicy`; always `authoritative` and non-citable. */
  registerAgentsPolicy(memberId: string, level: AgentsPolicyLevel): RegistrationOutcome;
  /** A reviewer-selected attachment as returned to the model: post-budget visible content, bound to the snapshot's content digest. */
  registerAttachment(memberId: string, attachment: Attachment, snapshotContentDigest: string): RegistrationOutcome;
  /** Auto-derived context (title, body, linked items, discussion) shown as intent; never citable. */
  registerIntent(memberId: string, label: string, text: string): RegistrationOutcome;
  /** Resume path (D8): reuse a prior attempt's identifier only when exact content, digest, and member snapshot all still match. */
  importRetainedSource(record: RetainedEvidenceRecord): RegistrationOutcome;
}

export interface EvidenceLedgerOptions {
  /** Defaults to `DEFAULT_HARNESS_POLICY`'s result and per-attempt evidence bounds. */
  policy?: Pick<HarnessPolicy, 'maxToolResultBytes' | 'maxEvidenceBytesPerAttempt'>;
}

/** Members straight from the immutable snapshot, so ledger identity can never drift from what the run pinned. */
export function ledgerMembersFromSnapshot(snapshot: ReviewRunSnapshot): EvidenceLedgerMember[] {
  return snapshot.members.map((member) => ({
    memberId: member.memberId,
    repositoryId: member.ref.repoId,
    baseSha: member.baseSha,
    headSha: member.headSha,
    changeRequestNumber: member.ref.number,
  }));
}

export function isCitableOrigin(origin: EvidenceOrigin): boolean {
  return CITABLE_ORIGINS.has(origin);
}

const SOURCE_ID_PATTERN = /^ev_[0-9a-f]{32}$/;

export function isWellFormedSourceId(value: unknown): value is string {
  return typeof value === 'string' && SOURCE_ID_PATTERN.test(value);
}

function mintSourceId(): string {
  return `ev_${randomBytes(16).toString('hex')}`;
}

function isPositiveInteger(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && value >= 1;
}

/** Bounded and normalized: positive integers, `endLine` defaults to `startLine`, and never inverted. */
export function normalizeEvidenceRange(startLine: unknown, endLine?: unknown): EvidenceRange | undefined {
  if (!isPositiveInteger(startLine)) return undefined;
  if (endLine === undefined) return { startLine, endLine: startLine };
  if (!isPositiveInteger(endLine) || endLine < startLine) return undefined;
  return { startLine, endLine };
}

/**
 * A literal `%2e`/`%2f`/`%5c` (case-insensitive) anywhere refuses the path
 * outright rather than decoding and re-checking it (task 9.8 "encoded" path
 * traversal): this module never resolves a path against a real filesystem
 * or URL, so a legitimate repository path has no reason to carry a
 * percent-encoded dot or separator, and fail-closed here costs nothing a
 * real path would ever need. A leading `/` is deliberately *not* refused --
 * it is stripped and the remainder treated as repository-relative, the same
 * normalization `modelVisiblePath.ts` uses for multi-root workspace labels
 * (`harnessEvidenceLedger.test.ts` pins `'/src/a.ts' -> 'src/a.ts'`).
 */
const ENCODED_TRAVERSAL_OR_SEPARATOR = /%(?:2e|2f|5c)/i;

/** Representation-only normalization plus a refusal of anything that could escape a repository root. */
export function normalizeEvidencePath(path: unknown): string | undefined {
  if (typeof path !== 'string') return undefined;
  const normalized = normalizeModelVisiblePath(path).replace(/^\//, '');
  if (normalized === '' || normalized.includes('\u0000')) return undefined;
  if (ENCODED_TRAVERSAL_OR_SEPARATOR.test(normalized)) return undefined;
  if (normalized.split('/').some((segment) => segment === '..')) return undefined;
  return normalized;
}

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
  }
  return value;
}

function utf8ByteLength(text: string): number {
  return Buffer.byteLength(text, 'utf8');
}

interface PendingRecord {
  kind: EvidenceKind;
  origin: EvidenceOrigin;
  trust: EvidenceTrust;
  revision?: PinnedRevision;
  path?: string;
  range?: EvidenceRange;
  completeness: EvidenceCompleteness;
  locations: readonly EvidenceLocation[];
  truncation?: EvidenceTruncation;
  exactContent: string;
  snapshotContentDigest?: string;
  /** Only `importRetainedSource` supplies these. */
  sourceId?: string;
  importedFromAttempt?: AttemptNumber;
}

function refuse(code: RegistrationRefusal, message: string): Refusal {
  return { ok: false, code, message };
}

function completenessOf<T>(result: InvestigationResult<T>): { completeness: EvidenceCompleteness; truncation?: EvidenceTruncation } | undefined {
  switch (result.state) {
    case 'complete':
      return { completeness: 'complete' };
    case 'paginated':
      return { completeness: 'paginated', truncation: { hasContinuation: true } };
    case 'truncated':
      return { completeness: 'truncated', truncation: { hasContinuation: false, knownRemainingUnits: result.knownRemainingUnits } };
    default:
      return undefined;
  }
}

export function createEvidenceLedger(
  identity: EvidenceLedgerIdentity,
  members: readonly EvidenceLedgerMember[],
  options: EvidenceLedgerOptions = {},
): EvidenceLedger {
  if (members.length === 0) throw new Error('An evidence ledger needs at least one member.');
  const memberIds = new Set<string>();
  for (const member of members) {
    if (memberIds.has(member.memberId)) throw new Error(`Duplicate ledger member id: ${member.memberId}`);
    memberIds.add(member.memberId);
  }
  const policy = options.policy ?? DEFAULT_HARNESS_POLICY;
  const maxResultBytes = policy.maxToolResultBytes;
  const maxEvidenceBytes = policy.maxEvidenceBytesPerAttempt;
  const frozenIdentity = deepFreeze({ ...identity });
  const frozenMembers = deepFreeze(members.map((member) => ({ ...member })));
  const byMemberId = new Map(frozenMembers.map((member) => [member.memberId, member] as const));

  const records: LedgerEvidenceSource[] = [];
  const bySourceId = new Map<string, LedgerEvidenceSource>();
  let bytesUsed = 0;

  function memberFor(memberId: string): EvidenceLedgerMember | undefined {
    return byMemberId.get(memberId);
  }

  function snapshotMatches(member: EvidenceLedgerMember, snapshot: InvestigationSnapshotRef): boolean {
    return snapshot.repoId === member.repositoryId && snapshot.baseSha === member.baseSha && snapshot.headSha === member.headSha;
  }

  /** The single append path: every invariant is checked here, whatever the origin. */
  function append(member: EvidenceLedgerMember, pending: PendingRecord): RegistrationOutcome {
    const byteLength = utf8ByteLength(pending.exactContent);
    if (byteLength > maxResultBytes) {
      return refuse('exceedsResultBound', `Payload is ${byteLength} bytes; one tool result may return at most ${maxResultBytes}.`);
    }
    if (bytesUsed + byteLength > maxEvidenceBytes) {
      return refuse('evidenceBudgetExhausted', `Registering ${byteLength} bytes would exceed the ${maxEvidenceBytes}-byte evidence budget for this attempt.`);
    }
    for (const location of pending.locations) {
      if (normalizeEvidencePath(location.path) !== location.path) return refuse('invalidPath', `Location path is not normalized: ${location.path}`);
      if (!normalizeEvidenceRange(location.range.startLine, location.range.endLine)) {
        return refuse('invalidRange', `Location range is not a bounded positive line range: ${location.path}`);
      }
    }
    if (pending.path !== undefined && normalizeEvidencePath(pending.path) !== pending.path) {
      return refuse('invalidPath', `Source path is not normalized: ${pending.path}`);
    }
    if (pending.range && !normalizeEvidenceRange(pending.range.startLine, pending.range.endLine)) {
      return refuse('invalidRange', 'Source range is not a bounded positive line range.');
    }
    const sourceId = pending.sourceId ?? mintSourceId();
    if (bySourceId.has(sourceId)) return refuse('duplicateSourceId', `Source ${sourceId} is already in this ledger.`);

    const source: LedgerEvidenceSource = deepFreeze({
      sourceId,
      digest: sha256Hex(pending.exactContent),
      kind: pending.kind,
      repositoryId: member.repositoryId,
      baseSha: member.baseSha,
      headSha: member.headSha,
      revision: pending.revision,
      path: pending.path,
      range: pending.range,
      completeness: pending.completeness,
      citable: isCitableOrigin(pending.origin),
      exactContent: pending.exactContent,
      runId: frozenIdentity.runId,
      lineageId: frozenIdentity.lineageId,
      attempt: frozenIdentity.attempt,
      memberId: member.memberId,
      origin: pending.origin,
      trust: pending.trust,
      sequence: records.length + 1,
      locations: pending.locations.map((location) => ({ ...location, range: { ...location.range } })),
      byteLength,
      truncation: pending.truncation,
      snapshotContentDigest: pending.snapshotContentDigest,
      importedFromAttempt: pending.importedFromAttempt,
    });
    records.push(source);
    bySourceId.set(sourceId, source);
    bytesUsed += byteLength;
    return { ok: true, source };
  }

  /** Common gate for every provider-backed result: member known, snapshot pinned to it, and a model-visible state. */
  function admitResult<T>(
    memberId: string,
    result: InvestigationResult<T>,
  ): { ok: true; member: EvidenceLedgerMember; value: T; completeness: EvidenceCompleteness; truncation?: EvidenceTruncation } | Refusal {
    const member = memberFor(memberId);
    if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
    if (!snapshotMatches(member, result.snapshot)) {
      return refuse('snapshotMismatch', `Result is pinned to ${result.snapshot.repoId}@${result.snapshot.baseSha}..${result.snapshot.headSha}, not member ${memberId}'s snapshot.`);
    }
    const shape = completenessOf(result);
    if (!shape) return refuse('notModelVisible', `A "${result.state}" result carries no content the model can see.`);
    return { ok: true, member, value: (result as { value: T }).value, ...shape };
  }

  function isRefusal(value: { ok: boolean }): value is Refusal {
    return value.ok === false;
  }

  const ledger: EvidenceLedger = {
    identity: frozenIdentity,
    members: frozenMembers,
    member: memberFor,
    get: (sourceId) => bySourceId.get(sourceId),
    sources: () => [...records],
    get size() {
      return records.length;
    },
    get bytesUsed() {
      return bytesUsed;
    },
    maxEvidenceBytes,

    registerDiffPage(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      const page = admitted.value;
      const path = normalizeEvidencePath(page.path);
      if (!path) return refuse('invalidPath', `Diff page path is not usable: ${String(page.path)}`);
      const locations: EvidenceLocation[] = [];
      for (const position of page.positions) {
        const positionPath = normalizeEvidencePath(position.path);
        const range = normalizeEvidenceRange(position.line, position.endLine);
        if (!positionPath) return refuse('invalidPath', `Diff position path is not usable: ${String(position.path)}`);
        if (!range) return refuse('invalidRange', `Diff position has an invalid line range at ${positionPath}.`);
        locations.push({ path: positionPath, range, side: position.side });
      }
      return append(admitted.member, {
        kind: 'diff',
        origin: 'diffPage',
        trust: 'untrusted',
        path,
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations,
        exactContent: page.patch,
      });
    },

    registerFileRange(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      const file = admitted.value;
      const path = normalizeEvidencePath(file.path);
      const range = normalizeEvidenceRange(file.startLine, file.endLine);
      if (!path) return refuse('invalidPath', `File range path is not usable: ${String(file.path)}`);
      if (!range) return refuse('invalidRange', `File range ${String(file.startLine)}-${String(file.endLine)} is not a bounded positive line range.`);
      return append(admitted.member, {
        kind: 'file',
        origin: 'fileRange',
        trust: 'untrusted',
        revision: file.revision,
        path,
        range,
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations: [{ path, range }],
        exactContent: file.text,
      });
    },

    registerRepositorySearch(memberId, request, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      if (!snapshotMatches(admitted.member, request.snapshot)) {
        return refuse('snapshotMismatch', 'Search request and result are pinned to different snapshots.');
      }
      const locations: EvidenceLocation[] = [];
      const canonicalMatches: Array<{ path: string; line: number; excerpt: string }> = [];
      for (const match of admitted.value) {
        const path = normalizeEvidencePath(match.path);
        const range = normalizeEvidenceRange(match.line);
        if (!path) return refuse('invalidPath', `Search match path is not usable: ${String(match.path)}`);
        if (!range) return refuse('invalidRange', `Search match line is invalid at ${path}.`);
        locations.push({ path, range });
        canonicalMatches.push({ path, line: match.line, excerpt: match.excerpt });
      }
      return append(admitted.member, {
        kind: 'searchExcerpt',
        origin: 'repositorySearch',
        trust: 'untrusted',
        revision: request.revision,
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations,
        exactContent: canonicalStringify(canonicalMatches),
      });
    },

    registerDiffSearch(memberId, request, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      if (!snapshotMatches(admitted.member, request.snapshot)) {
        return refuse('snapshotMismatch', 'Search request and result are pinned to different snapshots.');
      }
      const locations: EvidenceLocation[] = [];
      const canonicalMatches: Array<{ path: string; side: 'old' | 'new'; line: number; endLine?: number; excerpt: string }> = [];
      for (const match of admitted.value) {
        const path = normalizeEvidencePath(match.position.path);
        const range = normalizeEvidenceRange(match.position.line, match.position.endLine);
        if (!path) return refuse('invalidPath', `Diff search match path is not usable: ${String(match.position.path)}`);
        if (!range) return refuse('invalidRange', `Diff search match has an invalid line range at ${path}.`);
        locations.push({ path, range, side: match.position.side });
        canonicalMatches.push({ path, side: match.position.side, line: match.position.line, endLine: match.position.endLine, excerpt: match.excerpt });
      }
      return append(admitted.member, {
        kind: 'searchExcerpt',
        origin: 'diffSearch',
        trust: 'untrusted',
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations,
        exactContent: canonicalStringify(canonicalMatches),
      });
    },

    registerChangeRequestDetail(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      return append(admitted.member, {
        kind: 'detail',
        origin: 'changeRequestDetail',
        trust: 'untrusted',
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations: [],
        exactContent: canonicalStringify(admitted.value),
      });
    },

    registerIssueDetail(memberId, result) {
      const admitted = admitResult(memberId, result);
      if (isRefusal(admitted)) return admitted;
      return append(admitted.member, {
        kind: 'detail',
        origin: 'issueDetail',
        trust: 'untrusted',
        completeness: admitted.completeness,
        truncation: admitted.truncation,
        locations: [],
        exactContent: canonicalStringify(admitted.value),
      });
    },

    registerAgentsPolicy(memberId, level) {
      const member = memberFor(memberId);
      if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
      if (level.state !== 'present') return refuse('notModelVisible', `An "${level.state}" AGENTS.md level has no content.`);
      if (sha256Hex(level.content) !== level.digest) {
        return refuse('digestMismatch', 'AGENTS.md level digest does not match its content.');
      }
      const path = normalizeEvidencePath(level.directory === '' ? 'AGENTS.md' : `${level.directory}/AGENTS.md`);
      if (!path) return refuse('invalidPath', `AGENTS.md directory is not usable: ${level.directory}`);
      return append(member, {
        kind: 'file',
        origin: 'agentsPolicy',
        trust: 'authoritative',
        revision: 'base',
        path,
        completeness: 'complete',
        locations: [],
        exactContent: level.content,
      });
    },

    registerAttachment(memberId, attachment, snapshotContentDigest) {
      const member = memberFor(memberId);
      if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
      if (typeof attachment.content !== 'string') return refuse('malformed', 'Attachment has no content.');
      if (sha256Hex(attachment.content) !== snapshotContentDigest) {
        return refuse('digestMismatch', `Attachment ${attachment.id} does not match the content digest pinned in the run snapshot.`);
      }
      const visibleLength = Math.min(attachment.content.length, attachment.visibleContentLength ?? attachment.content.length);
      const exactContent = attachment.content.slice(0, visibleLength);
      const locations: EvidenceLocation[] = [];
      for (const entry of attachmentEvidenceManifest([attachment])) {
        const path = normalizeEvidencePath(entry.path);
        if (!path) return refuse('invalidPath', `Attachment evidence path is not usable: ${entry.path}`);
        for (const range of entry.ranges) {
          const normalized = normalizeEvidenceRange(range.startLine, range.endLine);
          if (!normalized) return refuse('invalidRange', `Attachment evidence range is invalid at ${path}.`);
          locations.push({ path, range: normalized });
        }
      }
      const path = normalizeEvidencePath(attachment.path);
      return append(member, {
        kind: 'attachment',
        origin: 'attachment',
        trust: 'untrusted',
        path,
        range: locations.length === 1 ? locations[0]?.range : undefined,
        completeness: visibleLength < attachment.content.length || attachment.truncated ? 'truncated' : 'complete',
        truncation: visibleLength < attachment.content.length || attachment.truncated ? { hasContinuation: false } : undefined,
        locations,
        exactContent,
        snapshotContentDigest,
      });
    },

    registerIntent(memberId, label, text) {
      const member = memberFor(memberId);
      if (!member) return refuse('unknownMember', `Member ${memberId} is not part of this run.`);
      if (typeof text !== 'string' || label.trim() === '') return refuse('malformed', 'Intent needs a label and text.');
      return append(member, {
        kind: 'detail',
        origin: 'intent',
        trust: 'untrusted',
        completeness: 'complete',
        locations: [],
        exactContent: canonicalStringify({ label, text }),
      });
    },

    importRetainedSource(record) {
      const member = memberFor(record.memberId);
      if (!member) return refuse('unknownMember', `Member ${record.memberId} is not part of this run.`);
      if (record.repositoryId !== member.repositoryId || record.baseSha !== member.baseSha || record.headSha !== member.headSha) {
        return refuse('snapshotMismatch', `Retained source ${record.sourceId} was fetched on a different repository or revision.`);
      }
      if (!isWellFormedSourceId(record.sourceId)) return refuse('malformed', 'Retained source identifier is not well-formed.');
      if (typeof record.exactContent !== 'string') {
        return refuse('exactContentUnavailable', `Retained source ${record.sourceId} has no exact content; it must be fetched again.`);
      }
      if (sha256Hex(record.exactContent) !== record.digest) {
        return refuse('digestMismatch', `Retained source ${record.sourceId} content no longer matches its digest.`);
      }
      if (!EVIDENCE_ORIGINS.includes(record.origin)) return refuse('malformed', `Unknown evidence origin: ${String(record.origin)}`);
      return append(member, {
        sourceId: record.sourceId,
        kind: record.kind,
        origin: record.origin,
        trust: record.origin === 'agentsPolicy' ? 'authoritative' : 'untrusted',
        revision: record.revision,
        path: record.path,
        range: record.range,
        completeness: record.completeness,
        truncation: record.truncation,
        locations: record.locations,
        exactContent: record.exactContent,
        snapshotContentDigest: record.snapshotContentDigest,
        importedFromAttempt: record.fetchedInAttempt,
      });
    },
  };

  return ledger;
}

/** What section 11 may persist for one source: everything except (optionally) the exact bytes. */
export function toRetainedEvidenceRecord(source: LedgerEvidenceSource, options: { includeExactContent: boolean }): RetainedEvidenceRecord {
  return {
    sourceId: source.sourceId,
    digest: source.digest,
    kind: source.kind,
    origin: source.origin,
    memberId: source.memberId,
    repositoryId: source.repositoryId,
    baseSha: source.baseSha,
    headSha: source.headSha,
    revision: source.revision,
    path: source.path,
    range: source.range,
    completeness: source.completeness,
    locations: source.locations,
    truncation: source.truncation,
    snapshotContentDigest: source.snapshotContentDigest,
    fetchedInAttempt: source.importedFromAttempt ?? source.attempt,
    exactContent: options.includeExactContent ? source.exactContent : undefined,
  };
}
